[project]
authors = ["Ian Zhang <yianzhang14@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "traffic"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
ipykernel = ">=6.29.5,<7"
matplotlib = ">=3.10.0,<4"
numpy = ">=2.2.2,<3"
pandas = ">=2.2.3,<3"
plotly = ">=5.24.1,<6"
pyarrow = ">=19.0.0,<20"
seaborn = ">=0.13.2,<0.14"
sortedcontainers = ">=2.4.0,<3"
shapely = ">=2.0.6,<3"
ipywidgets = ">=8.1.5,<9"
tqdm = ">=4.67.1,<5"
flask = ">=3.1.0,<4"
flask-cors = ">=5.0.0,<6"
scipy = ">=1.15.1,<2"
line_profiler = ">=4.1.3,<5"

[pypi-dependencies]
Flask-Pydantic = "*"
